#!/usr/bin/env bash

dir=$(pwd)
scriptname=$(basename "$0")

root=$(git rev-parse --show-toplevel 2> /dev/null)
if [[ $? != 0 ]]; then
  root="$dir"
fi
export GIT_DIR="$root/.todo"


# Helper functions
error() {
  case "$1" in
    need_copy )
      message='The command needs copy'
      code=3
      ;;
    not_setup )
      message='Todo not setup. Please run `todo init`'
      code=2
      ;;
    need_todo_id )
      message='You need to provide a todo #'
      code=4
      ;;
  esac
  echo "$message" 1>&2
  exit $code
}

is_setup() {
  [[ -d $root/.todo ]]
}

show() {
  format=$1
  shift
  git log --abbrev=4 --pretty=format:"$format" $@
}
show_as_done() {
  show "%C(green)%cn%C(reset)%C(auto) %s" $@
}
show_as_not_done() {
  show "%C(red)%cn%C(reset)%C(auto) %s" $@
}
show_with_id() {
  show "%C(auto)%h %cn %s" $@
}


# UI
usage="usage: $scriptname [<command>|todo]"
show_help() {
  echo $usage
  cat << EOF

Commands:
   new    Create new todo
   rm     Remove todo
   done   Tick off todo
EOF
}

setup() {
  git init --quiet --bare
  git update-ref refs/heads/root $(echo 'TODO' | git commit-tree $(git hash-object -t tree /dev/null))
  git update-ref refs/heads/todos root
  git update-ref refs/heads/ticked root
}

new_todo() {
  if [[ -z "$@" ]]; then
    error need_copy
  fi
  new_todo_sha=$(echo "$@" | GIT_COMMITTER_NAME=☐ git commit-tree $(git hash-object -t tree /dev/null) -p todos)
  git update-ref refs/heads/todos $new_todo_sha
  show_as_not_done $new_todo_sha^..$new_todo_sha
}

list_todos() {
  show_with_id root..todos
}

tick_todo() {
  if [[ -z "$1" ]]; then
    error need_todo_id
  else
    ticking_off_sha="$1"
  fi
  new_todo_sha=$(git show --format="%s" $ticking_off_sha | GIT_COMMITTER_NAME=☑ git commit-tree $(git hash-object -t tree /dev/null) -p ticked)
  previous_todo_sha=$(git log --max-count=1 --format="%h" $ticking_off_sha^)
  git update-ref refs/heads/ticked $new_todo_sha
  git update-ref refs/heads/todos $previous_todo_sha
  show_as_done $new_todo_sha^..$new_todo_sha
}

case "$1" in
  --help )
      show_help
    ;;
  help )
      show_help
    ;;
  init )
      shift
      setup $@
      echo "todo has been initialized in $GIT_DIR"
    ;;
  git )
      shift
      git "$@"
    ;;
  * )
    if ! is_setup; then
      error not_setup
    fi
    case "$1" in
      + )
          shift
          new_todo $@
        ;;
      \? )
          shift
          list_todos $@
        ;;
      = )
          shift
          tick_todo $@
        ;;
      * )
          if [[ -z "$@" ]]; then
            list_todos $@
          else
            new_todo $@
          fi
    esac
esac
